#!/bin/bash
apt-get -y install \
  apache2\
  chrony\
  git\
  glance\
  keystone\
  libapache2-mod-wsgi\
  mariadb-server\
  memcached\
  mongodb-clients\
  mongodb-server\
  nova-api\
  nova-conductor\
  nova-consoleauth\
  nova-novncproxy\
  nova-scheduler\
  openssl\
  python-memcache\
  python-openstackclient\
  python-pymongo\
  python-pymysql\
  rabbitmq-server\
  vim
